[server]
port = 5000
address = "0.0.0.0"
headless = true
runOnSave = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 5000

[theme]
base = "light"
