[server]
port = 5000
address = "0.0.0.0"
headless = true
runOnSave = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 5000

[client]
showSidebarNavigation = false

[theme]
base = "light"
primaryColor = "#3F51B5"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#212121"
font = "sans serif"
